settings:
  gui:
    padding_multiplicator: 0.6325301632983623
    text_font_size: 18
    title_font_size: 34
  modes:
    back_front: true
    front_back: true
    letter_salad: true
    multiple_choice: true
