settings:
  gui:
    padding_multiplicator: 0.6154463077780131
    text_font_size: 21
    title_font_size: 34
  modes:
    back_front: true
    connect_pairs: true
    front_back: true
    letter_salad: true
    multiple_choice: true
    syllable_salad: true
    typing: true
  session_size: 500
  theme:
    base_preset: dark
    custom_colors: {}
    preset: dark
stats:
  total_learn_time_seconds: 1000000000102
